### ISSUE TITLE
Resulting bin uses much more ram than IDE compiled bin

### ISSUE THREAD

**Issue by polandj** [plerup/makeEspArduino#107] opened 2019-02-18 01:38 UTC
Not sure if this is related to the latest 2.5.0 ESP update, but after that update is when I noticed it. 

When I use the Arduino IDE to compile:

> Sketch uses 555448 bytes (53%) of program storage space. Maximum is 1044464 bytes.
> Global variables use 37580 bytes (45%) of dynamic memory, leaving 44340 bytes for local variables. Maximum is 81920 bytes.

When I use makeEspArduino:

> Memory usage
>   Ram:    42080 bytes
>   Flash: 556308 bytes
> 
> LwIPVariant: v2 Lower Memory

Using BOARD=nodemcuv2 and FLASH_DEF=4M2M.  Any ideas?  I hate using the IDE, but I need that ~5K of ram...

**Comment by luffykesh** [comment] 2019-04-19 19:14
I observed the same @plerup , when built from IDE:
RAM - 36588  bytes
FLASH - 360632  bytes

When build by makeEspArduino:
Memory usage
  Ram:    40648 bytes
  Flash: 360604 bytes

**Comment by plerup** [comment] 2020-01-01 19:48
Confirmed. Sorry for the long delay in responding.
This is due to Arduino IDE putting all the object files into an archive, whereas makeEspArduino sends them directly to the linker. This seems to affect the linker's ability to remove unused variables. It will be fixed in next commit, coming shortly.

**Comment by plerup** [comment] 2020-01-02 20:21
Fixed in latest commit

**Closed by plerup** 2020-01-02 20:21 UTC

**Comment by polandj** [comment] 2020-01-02 20:45
Hope to try it out soon.  Thanks so much!  Happy new year!
